services:
  # backend:
  #   build: .
  #   ports:
  #     - "${PORT:-8080}:${PORT:-8080}"
  #   depends_on:
  #     - postgres
  #     - redis
  #   env_file:
  #     - .env
  #   networks:
  #     - dahaa_network

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - dahaa_network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    # networks:
    #   - dahaa_network

# networks:
#   dahaa_network:
#     driver: bridge

volumes:
  postgres_data:
  redis_data:
